### ISSUE TITLE
Interrogantes

### ISSUE THREAD

**Issue by GorreriFranco** [pdep-utn-frd/presentacion-2021-javitojavitox#1]
Javito o Javitox

Al terminar de leer tu presentacion me surgiero unos interrogantes.

1. Jugaste al Scrap Mechanic? Juegazo
2. Fecha de nacimiento vendrá en una nueva versión del documento?
3. Seccion Mascotas: El diminutivo es cariñoso o dennota el tamaño del animal? Sería una coincidencia que todos sean todos chiquititos. Y si son todos chiquititos, no es lo mismo que ninguno sea chiquitito? Osea con qué los estas comparando? Yo tengo un gatito pero ahora me entro la duda si en comparación a los tuyos, el mio es chiquitito o grande, o enorme!

**Comment by JavierAlbertoBenitez** [comment]
No, no jugué al Scrap Mechanic. Ya actualice la fecha de nacimiento y el nombre diminutivo de mi mascotas es de forma cariñosa.

**Comment by GorreriFranco** [comment]
Nanana yo cumplo el 18 de noviembre
