### ISSUE TITLE
Abstracción 

### ISSUE THREAD

**Issue by tomi1368** [pdep-utn-frd/presentacion-2021-javitojavitox#3]
<h1><em>Hola Javi</em></h1>
<p>Al ver tu perfil siento como que hay información que sobra si usas tu <b>GitHub</b> como <i>Portfolio</i> <br> Saludos.</p>

**Comment by JavierAlbertoBenitez** [comment]
Hola, gracias por la recomendación ¿Cuál información sobraría?
