### ISSUE TITLE
pequeños cambios hacen la diferencia

### ISSUE THREAD

**Issue by francohilt** [pdep-utn-frd/presentacion-2021-javitojavitox#4]
Hola Javi, buena presentación! Fíjate cuando escribiste --> "Trabajo en: En el" repetiste "en" quizás pudieras dejar solo "trabajo" como ítem. Además para que no sea todo un bloque, puedes usar negritas usando  ** al incido y final de cada palabra. Por ejemplo **Edad** : 20 años.
pd: En fecha de nacimiento lo dejaste vacío.
Saludos!

**Comment by JavierAlbertoBenitez** [comment]
Hola, gracias por la ayuda ya solucione ese error de tipeo y agregue las negritas
